# Generated by Django 4.0 on 2022-01-02 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('part_number', models.PositiveIntegerField(null=True)),
                ('board_id', models.PositiveIntegerField(null=True)),
                ('anime_id', models.PositiveIntegerField(null=True)),
                ('manga_id', models.PositiveIntegerField(null=True)),
                ('club_id', models.PositiveIntegerField(null=True)),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(15)])),
                ('topic_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('board_id__isnull', False), ('club_id__isnull', False), ('anime_id__isnull', False), ('manga_id__isnull', False), _connector='OR'), name='post_board_id_or_club_id_or_anime_id_or_manga_id_not_null'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(('part_number__isnull', True), models.Q(models.Q(('anime_id__isnull', False), ('manga_id__isnull', False), _connector='OR'), ('part_number__isnull', False)), _connector='OR'), name='anime_id_or_manga_id_must_exist_if_part_number_exists'),
        ),
    ]
