# Generated by Django 4.0 on 2022-01-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_queue', '0002_post_created_post_topic_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anime_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='board_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='club_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='manga_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='part_number',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic_created',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
