# Generated by Django 4.0 on 2022-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_queue', '0004_alter_post_anime_id_alter_post_board_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('anime_id__isnull', True), ('board_id__isnull', False), ('club_id__isnull', True), ('manga_id__isnull', True)), models.Q(('anime_id__isnull', True), ('board_id__isnull', True), ('club_id__isnull', False), ('manga_id__isnull', True)), models.Q(('anime_id__isnull', False), ('board_id__isnull', True), ('club_id__isnull', True), ('manga_id__isnull', True)), models.Q(('anime_id__isnull', True), ('board_id__isnull', True), ('club_id__isnull', True), ('manga_id__isnull', False)), _connector='OR'), name='only_one_of_board_id_or_club_id_or_anime_id_or_manga_id_must_exist'),
        ),
    ]
